//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impresoras
    {
        public int IdEquipoImpresora { get; set; }
        public int IdDepto { get; set; }
        public string Tipo { get; set; }
        public string Marcar { get; set; }
        public string Modelo { get; set; }
        public string Arrendamiento { get; set; }
        public Nullable<byte> PuertoEthetnet { get; set; }
        public Nullable<byte> PuertoUSB { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Depto Depto { get; set; }
    }
}
