//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public int IdMonitor { get; set; }
        public Nullable<int> IdEquipoComputo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string NoSerie { get; set; }
        public string Pulgada { get; set; }
        public string NoPuertoVGA { get; set; }
        public string NoPuertoHDMI { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual EquipoComputo EquipoComputo { get; set; }
    }
}
